#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

c_bg_0="#1d2021"
c_bg="#282828"
c_bg_2="#504945"
c_fg="#bdae93"
c_urgent="#cc241d"

xsetroot -solid "$c_bg_0"

# remove all existing keybindings
hc keyunbind --all

Mod=Mod4

hc keybind $Mod-Shift-apostrophe close
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-Return spawn kitty -- tmux new-session -A -s main
hc keybind $Mod-e spawn rofi -show run
hc keybind $Mod-p spawn flameshot gui
hc keybind $Mod-m spawn slock

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
# hc keybind $Mod-u       split   bottom  0.5
# hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc set default_frame_layout vertical
hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-F$key" chain , \
               set swap_monitors_to_get_tag true ,  \
               use_index "$i" , \
               set swap_monitors_to_get_tag false
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-o set_layout max
hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-p pseudotile toggle
hc keybind $Mod-Control-m jumpto last-minimized

hc keybind $Mod-v       split   bottom  0.5
hc keybind $Mod-d       split   right   0.5
hc keybind $Mod-Shift-d spawn /usr/share/doc/herbstluftwm/examples/toggledualhead.sh

hc keybind $Mod-period                                                          \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_width 0
# hc set frame_border_active_color '#ignored'
# hc set frame_border_normal_color '#ignored'

hc set frame_bg_normal_color "$c_bg_2"
hc set frame_bg_active_color "$c_fg"
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.title_height 15
hc attr theme.title_when never
hc attr theme.title_font 'monospace:pixelsize=12'  # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.title_depth 3  # space below the title's baseline
hc attr theme.active.color "$c_fg"
hc attr theme.title_color "$c_bg"
hc attr theme.normal.color "$c_bg"
hc attr theme.urgent.color "$c_urgent"
hc attr theme.tab_color "$c_bg"
hc attr theme.active.tab_color "$c_bg"
hc attr theme.active.tab_outer_color "$c_bg"
hc attr theme.active.tab_title_color "$c_fg"
hc attr theme.active.title_then always
hc attr theme.normal.title_color "$c_fg"
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color "$c_fg"
hc attr theme.urgent.inner_color "$c_urgent"
hc attr theme.normal.inner_color "$c_bg"
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 1
hc attr theme.background_color "$c_bg"

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings on
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 1

# rules
hc unrule -F
hc rule focus=on

hc rule class='microsoft teams - preview' tag=4

hc rule class='jetbrains-idea' tag=5

hc rule class='Lutris' tag=7

hc rule class='keepassxc' tag=9
hc rule class='discord' tag=9
hc rule class='Steam' tag=9
hc rule class='TelegramDesktop' tag=9
hc rule class='Signal' tag=9

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on floatplacement=none
hc rule instance~'yubioath-desktop' floating=on floatplacement=none

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
hc set auto_detect_monitors 1
hc set focus_follows_mouse on
hc set swap_monitors_to_get_tag false
# hc set show_frame_decorations focused_if_multiple

xset r rate 300 60

killall polybar
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
  MONITOR=$m polybar --reload herbstluftwm -c ~/.config/polybar/polybar.config &
done
