[[block]]
block = "sound"

[[block]]
block = "custom"
command = 'pactl list sources | grep -A 10 $(pactl info | grep "Default Source" | cut -f3 -d" ") | grep -c "Mute: yes" > /dev/null && echo  || echo '
interval = 5
[[block.click]]
button = "left"
cmd = "pactl set-source-mute @DEFAULT_SOURCE@ toggle"
update = true

[[block]]
block = "load"
interval = 3
format = "  $1m.eng(w:4) "

[[block]]
block = "memory"
interval = 30
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "disk_space"
path = "/home"
format = " /home $available "
interval = 20
warning = 15.0
alert = 5.0

[[block]]
block = "net"
format = " $ip "
interval = 600

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%b %d %H:%M:%S') "
